CREATE TABLE IF NOT EXISTS "user"(
  userId VARCHAR(255) PRIMARY KEY, 
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  membership SMALLINT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  updatedAt TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "category"(
  categoryId VARCHAR(255) PRIMARY KEY, 
  name VARCHAR(255) NOT NULL,
  description VARCHAR(1000) NULL,
  activated BOOLEAN NOT NULL DEFAULT false,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  updatedAt TIMESTAMP NULL
);
CREATE TABLE IF NOT EXISTS "post"(
  postId VARCHAR(255) PRIMARY KEY, 
  title VARCHAR(255) NOT NULL,
  body VARCHAR(1000) NOT NULL,
  categoryId VARCHAR(255) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 0,
  label SMALLINT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  updatedAt TIMESTAMP NULL,
  CONSTRAINT fkCategory
    FOREIGN KEY(categoryId)
      REFERENCES category(categoryId)
);
CREATE TABLE IF NOT EXISTS "payment"(
  paymentId VARCHAR(255) PRIMARY KEY, 
  amount INT NOT NULL,
  paymentMethod VARCHAR(255) NOT NULL,
  status VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT now(),
  updatedAt TIMESTAMP NULL
);